# Generated by Django 5.1.3 on 2025-08-08 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('CONSULTATION', 'CONSULTATION'), ('PSYCHOTERAPIE ', 'PSYCHOTERAPIE'), ('CONTROLE', 'CONTROLE')], max_length=100, null=True)),
                ('date_consultation', models.DateTimeField()),
                ('diagnostic', models.TextField()),
                ('traitement', models.TextField(blank=True)),
                ('notes_medecin', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('planifie', 'Planifiée'), ('en_cours', 'En cours'), ('termine', 'Terminée'), ('annule', 'Annulée')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patient')),
            ],
        ),
    ]
