# Generated by Django 5.1.3 on 2025-08-09 10:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_consultation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date_consultation']},
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 9, 11, 7, 21, 372431)),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnostic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='notes_medecin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='website.patient'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='statut',
            field=models.CharField(choices=[('planifie', 'planifie'), ('en_cours', 'en_cours'), ('termine', 'termine'), ('rapporte', 'rapporte'), ('annule', 'annule')], default='planifie', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='traitement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='type',
            field=models.CharField(choices=[('consultation', 'consultation'), ('psychoterapie', 'psychoterapie'), ('controle', 'controle')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
