# Generated by Django 5.1.3 on 2025-08-09 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
