# Generated by Django 5.1.3 on 2025-08-22 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_patient_age_patient_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('consultation', 'Consultation'), ('controle', 'Contrôle'), ('seance_psycho', 'Séance Psychotérapique')], help_text='Le prix sera automatiquement calculé selon le type', max_length=50)),
                ('date_consultation', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('rapporte', 'Reporté'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='website.patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
