# Generated by Django 5.1.3 on 2025-08-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_ordonnance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ordonnance',
            name='uniq_numero_ordonnance_par_patient',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='consultation',
            field=models.OneToOneField(blank=True, help_text='Consultation associée (facultatif : une consultation a au plus une ordonnance).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnance', to='website.consultations'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure de création (remplie automatiquement).'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='description',
            field=models.TextField(help_text='Contenu libre de l’ordonnance : médicaments, posologies, durées, consignes.'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='numero',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Numéro d’ordonnance séquentiel pour ce patient (attribué automatiquement).', null=True),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(help_text='Patient auquel appartient cette ordonnance.', on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='website.patient'),
        ),
        migrations.AddConstraint(
            model_name='ordonnance',
            constraint=models.UniqueConstraint(fields=('patient', 'numero'), name='uniq_numero_ordonnance_par_patient'),
        ),
    ]
