# Generated by Django 5.1.3 on 2025-08-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_ordonnance_uniq_numero_ordonnance_par_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='numero',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='consultations',
            constraint=models.UniqueConstraint(fields=('patient', 'numero'), name='uniq_numero_consultation_par_patient'),
        ),
    ]
